model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/1MNM.pdb
    chain_id: C
  state2:
    pdb_path: package://benchmarks/pdb/1MNM.pdb
    chain_id: D
alignment:
  state1: "(1, 77)"
  state2: "(1, 77)"
sequence_recovery:
  target_sequences:
    - "GLVFNVVTQDMINKSTKPYRGHRFTKENVRILESWFAKNIENPYLDTKGLENLMKNTSLSRIQIKNWVSNRRRKEKT"
    - "GLVFNVVTQDMINKSTKPYRGHRFTKENVRILESWFAKNIENPYLDTKGLENLMKNTSLSRIQIKNWVSNRRRKEKT"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/2OUG.pdb
    chain_id: C
  state2:
    pdb_path: package://benchmarks/pdb/6S3Q.pdb
    chain_id: A
