model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/1WCW.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/1WD7.pdb
    chain_id: B
alignment:
  state1: "(1, 254)"
  state2: "(2, 255)"
sequence_recovery:
  target_sequences:
    - "AVRVAYAGLRRKEAFKALAEKLGFTPLLFPVQATEKVPVPEYRDQVRALAQGVDLFLATTGVGVRDLLEAGKALGLDLEGPLAKAFRLARGAKAARALKEAGLPPHAVGDGTSKSLLPLLPQGRGVAALQLYGKPLPLLENALAERGYRVLPLMPYRHLPDPEGILRLEEALLRGEVDALAFVAAIQVEFLFEGAKDPKALREALNTRVKALAVGRVTADALREWGVKPFYVDETERLGSLLQGFKRALQKEVA"
    - "AVRVAYAGLRRKEAFKALAEKLGFTPLLFPVQATEKVPVPEYRDQVRALAQGVDLFLATTGVGVRDLLEAGKALGLDLEGPLAKAFRLARGAKAARALKEAGLPPHAVGDGTSKSLLPLLPQGRGVAALQLYGKPLPLLENALAERGYRVLPLMPYRHLPDPEGILRLEEALLRGEVDALAFVAAIQVEFLFEGAKDPKALREALNTRVKALAVGRVTADALREWGVKPFYVDETERLGSLLQGFKRALQKEVA"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/6NC9.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/6E9N.pdb
    chain_id: B
