model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/2KXO-1.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/3R9J.pdb
    chain_id: C
alignment:
  state1: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82]
  state2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70]
sequence_recovery:
  target_sequences:
    - "KTATVARDRLQIIIAQRAQEGQTPDYLPTLRKALMEVLSKYVNVSLDNIRISQEKQDGMDVLELNITLP"
    - "NTANIAKERLQNIVAERRRSDAEPHYLPQLRKDILEVICKYVQIDPEMVTVQLEQKDDISILELNVTLP"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/4TSY.pdb
    chain_id: D
  state2:
    pdb_path: package://benchmarks/pdb/4PJ1.pdb
    chain_id: A
