model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/2P3V.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/2P3V.pdb
    chain_id: D
alignment:
  state1: "(1, 254)"
  state2: "(1, 254)"
sequence_recovery:
  target_sequences:
    - "MDRLDFSIKLLRKVGHLLMIHWGRVDNVEKKTGFKDIVTEIDREAQRMIVDEIRKFFPDENIMAEEGIFEKGDRLWIIDPIDGTINFVHGLPNFSISLAYVENGEVKLGVVHAPALNETLYAEEGSGAFFNGERIRVSENASLEECVGSTGSYVDFTGKFIERMEKRTRRIRILGSAALNAAYVGAGRVDFFVTWRINPWDIAAGLIIVKEAGGMVTDFSGKEANAFSKNFIFSNGLIHDEVVKVVNEVVEEIG"
    - "MDRLDFSIKLLRKVGHLLMIHWGRVDNVEKKTGFKDIVTEIDREAQRMIVDEIRKFFPDENIMAEEGIFEKGDRLWIIDPIDGTINFVHGLPNFSISLAYVENGEVKLGVVHAPALNETLYAEEGSGAFFNGERIRVSENASLEECVGSTGSYVDFTGKFIERMEKRTRRIRILGSAALNAAYVGAGRVDFFVTWRINPWDIAAGLIIVKEAGGMVTDFSGKEANAFSKNFIFSNGLIHDEVVKVVNEVVEEIG"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/2FY7.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/4Q4A.pdb
    chain_id: B
