model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/5EQD.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/5EQD.pdb
    chain_id: B
alignment:
  state1: "(2, 392)"
  state2: "(1, 391)"
sequence_recovery:
  target_sequences:
    - "GNFDLFVVGSGFFGLTIAERAATQLGKRVLVIERRPHIGGNAYSEPEPETGIEVHKYGAHLFHTSNKRVWDYVRQFTDFTGYQHRVFAMHNGQAYQFPMGLGLVSQFFGRYFSPDEARALIAEQASEIDTKDAKNFEEKAISLVGRPLYEAFIKHYTAKQWQTDPKDLPASNITRLPVRYTFDNRYFNDTYEGLPVEGYTKWLENMAADERIEVRLDTDWFDVRDDLRAANPDAPVVYTGPLDRYFDYAEGRLGWRTLDFELEVLETGDFQGTPVMNYNDLDVPYTRIHEFRHFHPERTYPTDKTVIMREYSRFADNDDEPYYPINTEADRAVLAAYRARAKAETASAKVLFGGRLGTYQYLDMHMAIASALSMFDNVLAPHLSEGASLVT"
    - "GNFDLFVVGSGFFGLTIAERAATQLGKRVLVIERRPHIGGNAYSEPEPETGIEVHKYGAHLFHTSNKRVWDYVRQFTDFTGYQHRVFAMHNGQAYQFPMGLGLVSQFFGRYFSPDEARALIAEQASEIDTKDAKNFEEKAISLVGRPLYEAFIKHYTAKQWQTDPKDLPASNITRLPVRYTFDNRYFNDTYEGLPVEGYTKWLENMAADERIEVRLDTDWFDVRDDLRAANPDAPVVYTGPLDRYFDYAEGRLGWRTLDFELEVLETGDFQGTPVMNYNDLDVPYTRIHEFRHFHPERTYPTDKTVIMREYSRFADNDDEPYYPINTEADRAVLAAYRARAKAETASAKVLFGGRLGTYQYLDMHMAIASALSMFDNVLAPHLSEGASLVT"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/6X3E.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/6QV1.pdb
    chain_id: B
