model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/5MKK.pdb
    chain_id: B
  state2:
    pdb_path: package://benchmarks/pdb/6RAJ.pdb
    chain_id: B
alignment:
  state1: "(3, 575)"
  state2: "(1, 573)"
sequence_recovery:
  target_sequences:
    - "RSAAPLLRRLWPYVGRYRWRYLWAVLAGLVSIFFFVLTPYFLRLAVDAVQAGRGFGVYALAIVASAALSGLLSYAMRRLAVVASRQVEYDLRRDLLHHLLTLDRDFYHKHRVGDLMNRLNTDLSAVREMVGPGILMGSRLSFLVLLAFLSMYAVNARLAFYLTLILPGIFLAMRFLLRLIDRRYREAQEVFDRISTLAQEAFSGIRVVKGYALERRMVAWFQDLNRLYVEKSLALARVEGPLHALLGFLMGFAFLTVLWAGGAMVVRGELSVGELVQFNAYLAQLTWPILGLGWVMALYQRGLTSLRRLFELLDEKPAIRDEDPLPLALEDLSGEVRFEGVGLKRDGRWLLRGLTLTIPEGMTLGITGRTGSGKSLLAALVPRLLDPSEGRVYVGGHEARRIPLAVLRKAVGVAPQEPFLFSETILENIAFGLDEVDRERVEWAARLAGIHEEILAFPKGYETVLGERGITLSGGQRQRVALARALAKRPKILILDDALSAVDAETEARILQGLKTVLGKQTTLLISHRTAALRHADWIIVLDGGRIVEEGTHESLLQAGGLYAEMDRLQKEV"
    - "RSAAPLLRRLWPYVGRYRWRYLWAVLAGLVSIFFFVLTPYFLRLAVDAVQAGRGFGVYALAIVASAALSGLLSYAMRRLAVVASRQVEYDLRRDLLHHLLTLDRDFYHKHRVGDLMNRLNTDLSAVREMVGPGILMGSRLSFLVLLAFLSMYAVNARLAFYLTLILPGIFLAMRFLLRLIDRRYREAQEVFDRISTLAQEAFSGIRVVKGYALERRMVAWFQDLNRLYVEKSLALARVEGPLHALLGFLMGFAFLTVLWAGGAMVVRGELSVGELVQFNAYLAQLTWPILGLGWVMALYQRGLTSLRRLFELLDEKPAIRDEDPLPLALEDLSGEVRFEGVGLKRDGRWLLRGLTLTIPEGMTLGITGRTGSGKSLLAALVPRLLDPSEGRVYVGGHEARRIPLAVLRKAVGVAPQEPFLFSETILENIAFGLDEVDRERVEWAARLAGIHEEILAFPKGYETVLGERGITLSGGQRQRVALARALAKRPKILILDDALSAVDAETEARILQGLKTVLGKQTTLLISHRTAALRHADWIIVLDGGRIVEEGTHESLLQAGGLYAEMDRLQKEV"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/4CMQ.pdb
    chain_id: B
  state2:
    pdb_path: package://benchmarks/pdb/4ZT0.pdb
    chain_id: C
