model_ref: /path/to/model.ckpt
af3_evaluate: true
af3:
  model_seeds: [0, 1, 2]
targets:
  state1:
    pdb_path: package://benchmarks/pdb/6HNI.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/6HNJ.pdb
    chain_id: A
alignment:
  state1: "(1, 295)"
  state2: "(2, 296)"
sequence_recovery:
  target_sequences:
    - "VKKIGITQLVEHPALDATRTGFVKALEKNGFKDGENIDIDFQNAQNDMPTTQSIASKFASDKKDLIFAISTPSAQAAFNATKDIPILITAVSDPVAAGLVKTLEKPGTNVSGTSDFVSVDKGLELLKIFAPKAKTIGVMYNTSEVNSKVQVDALKEYASKNGFKVVEKGITTSNEVNQGISSLVGKIDVLYVPTDNLVASSMPIVSKIATENKIPVIAAESGPVEKGALACQGINYEKLGYKTGEMAVKILNGESVSDMPVATSDDTDIIVNEDILKALGMEKPSNENISYVKTK"
    - "VKKIGITQLVEHPALDATRTGFVKALEKNGFKDGENIDIDFQNAQNDMPTTQSIASKFASDKKDLIFAISTPSAQAAFNATKDIPILITAVSDPVAAGLVKTLEKPGTNVSGTSDFVSVDKGLELLKIFAPKAKTIGVMYNTSEVNSKVQVDALKEYASKNGFKVVEKGITTSNEVNQGISSLVGKIDVLYVPTDNLVASSMPIVSKIATENKIPVIAAESGPVEKGALACQGINYEKLGYKTGEMAVKILNGESVSDMPVATSDDTDIIVNEDILKALGMEKPSNENISYVKTK"
decoys:
  state1:
    pdb_path: package://benchmarks/pdb/4LP5.pdb
    chain_id: A
  state2:
    pdb_path: package://benchmarks/pdb/4CMQ.pdb
    chain_id: B
